### PR TITLE
Add translation support and Hungarian localization

### LINKED ISSUE #79: Add translation support
I would like to translate this app into my native language but it seams the [strings.xml](https://github.com/hauke96/GeoNotes/blob/main/app/src/main/res/values/strings.xml) is not up-to-date and most the strings are missing. Can you please update the file?

### PR DESCRIPTION
**Pull request by meskobalazs**
I have moved all the strings to `strings.xml` and also added Hungarian localization (partly for test reasons). I have also marked the preference keys as non-translatable as it made sense to me.

Fixes #79

### CODE REVIEW

**Comment by hauke96** [comment]
Hi, thanks for the translation! I'm quite busy right now but reviewing and testing this is on my todo-list.

**Comment by hauke96** [comment]
Thanks again for the translation, I merged it, so it'll be part of the next release.

**Comment by meskobalazs** [comment]
Thanks!

**Comment by hauke96** [comment]
Just forgot to mention it: Some newer strings aren't translated yet, I added TODOs at the locations in the ` values-hu/strings.xml` file. Feel free to submit a PR with the translations.

**Pull request merged**
